### ISSUE TITLE
No such file or directory: '/home/MYUSERNAME/Downloads/kernel/linux'

### ISSUE THREAD

**Issue by ErikReider** [AcidzDev/Ubuntu-Fix127#1]
Hi!
I'm getting this error while trying to compile the kernel. Any ideas on my?

linux-5.3.5/virt/lib/irqbypass.c
Traceback (most recent call last):
  File "./Ubuntu-Patcher.py", line 48, in <module>
    os.chdir(homedir+"/Downloads/kernel/linux")
FileNotFoundError: [Errno 2] No such file or directory: '/home/erikreider/Downloads/kernel/linux'

**Comment by AcidzDev** [comment]
Hi, can you check what version of python you are using with `python -version`

**Comment by AcidzDev** [comment]
Fixed the bug and confirmed that it works
